-- Phodio / Soulprint PostgreSQL schema for Supabase
-- Run this entire file in Supabase SQL Editor.
-- It preserves the existing table names and sample records from studio_mgmt.sql.

CREATE TABLE IF NOT EXISTS admin (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(100),
    lastname VARCHAR(100),
    username VARCHAR(150) UNIQUE,
    phone VARCHAR(11) UNIQUE,
    password VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    profile_image VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(255) NOT NULL,
    service_type VARCHAR(80),
    package_key VARCHAR(80),
    package_type VARCHAR(100),
    motif VARCHAR(100),
    price NUMERIC(10,2),
    booking_date DATE,
    start_time TIME,
    slot_period VARCHAR(2) CHECK (slot_period IN ('AM','PM') OR slot_period IS NULL),
    color_code VARCHAR(7),
    attendee_count SMALLINT NOT NULL DEFAULT 1 CHECK (attendee_count >= 0),
    client_notes TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'Confirmed',
    status_note TEXT,
    status_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT booking_day_slot UNIQUE (booking_date, slot_period)
);

CREATE INDEX IF NOT EXISTS bookings_client_status ON bookings (client_id, status);
CREATE INDEX IF NOT EXISTS bookings_date_status ON bookings (booking_date, status);

CREATE TABLE IF NOT EXISTS booking_updates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL,
    note TEXT NOT NULL,
    actor_type VARCHAR(10) NOT NULL DEFAULT 'system' CHECK (actor_type IN ('client','admin','system')),
    actor_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS booking_updates_booking_id ON booking_updates (booking_id);

CREATE TABLE IF NOT EXISTS daily_tracker (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_date DATE NOT NULL UNIQUE,
    income_today NUMERIC(10,2) NOT NULL,
    client_today INTEGER NOT NULL,
    target NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    expense_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS liabilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creditor VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    due_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Existing sample data. ON CONFLICT makes this safe to run again.
INSERT INTO admin (id, username, password, created_at) VALUES
(1, 'soulprint', '$2y$10$q6Z2W6O1hReODtJEmkfdFuZnOBhPx4/Aff.//ul1F.lwHV8rIZCw.', '2026-03-18 16:41:25+08')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, firstname, lastname, username, phone, password, created_at, profile_image) VALUES
(1, 'Romano', 'Datinguinoo', 'datinguinooromano@gmail.com', '09703947838', '$2y$10$R38BmED/3vtbX9w1EJPYNe9PUDMJI/LZwYGmHkYVo1nKLqjSHiLzi', '2026-03-28 12:30:06+08', NULL),
(2, 'Mano', 'Datinguinoo', 'datinguinoomano@gmail.com', '09874564357', '$2y$10$10zOzqEX6I3hPBzhlDbcH.Y32GwHRHFe8fGlmISVNhqhr5eRqWGWK', '2026-03-28 12:49:22+08', 'profile_69c7ce52956721.50589209.jpg')
ON CONFLICT (id) DO NOTHING;

INSERT INTO bookings (id, client_id, title, service_type, package_key, package_type, motif, price, booking_date, start_time, slot_period, color_code, attendee_count, status, status_note, status_updated_at) VALUES
(1, 2, 'Princess portrait session', 'portrait', 'self_solo', 'Self Photography — Solo', 'Princess', 350.00, '2026-03-30', '09:42:00', NULL, '#3b82f6', 1, 'Confirmed', 'Imported appointment', '2026-03-30 09:00:00+08'),
(2, 2, 'Graduation portrait session', 'graduation', 'self_solo', 'Self Photography — Solo', 'Graduation', 350.00, '2026-03-30', '09:43:00', NULL, '#3b82f6', 1, 'Confirmed', 'Imported appointment', '2026-03-30 09:00:00+08')
ON CONFLICT (id) DO NOTHING;

INSERT INTO booking_updates (id, booking_id, status, note, actor_type, created_at) VALUES
(1, 1, 'Confirmed', 'Imported appointment', 'system', '2026-03-30 09:00:00+08'),
(2, 2, 'Confirmed', 'Imported appointment', 'system', '2026-03-30 09:00:00+08')
ON CONFLICT (id) DO NOTHING;

-- Keep generated IDs above the imported records.
SELECT setval(pg_get_serial_sequence('admin','id'), COALESCE((SELECT MAX(id) FROM admin), 1), true);
SELECT setval(pg_get_serial_sequence('users','id'), COALESCE((SELECT MAX(id) FROM users), 1), true);
SELECT setval(pg_get_serial_sequence('bookings','id'), COALESCE((SELECT MAX(id) FROM bookings), 1), true);
SELECT setval(pg_get_serial_sequence('booking_updates','id'), COALESCE((SELECT MAX(id) FROM booking_updates), 1), true);

-- Keep updated_at behavior equivalent to the original MySQL ON UPDATE column.
CREATE OR REPLACE FUNCTION phodio_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS bookings_set_updated_at ON bookings;
CREATE TRIGGER bookings_set_updated_at
BEFORE UPDATE ON bookings
FOR EACH ROW EXECUTE FUNCTION phodio_set_updated_at();

-- The PHP application owns authentication and server-side authorization.
-- Keep the tables private from browser-side Supabase clients unless you later
-- decide to migrate authentication/data access to the Supabase Data API.
ALTER TABLE admin ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_tracker ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE liabilities ENABLE ROW LEVEL SECURITY;
